# Generated by Django 5.2.8 on 2025-11-11 09:02

import core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.CharField(default=core.models.chatid, editable=False, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=50, unique=True)),
                ('companyname', models.CharField(max_length=200)),
                ('JoinedDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chatroom')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CSRRep',
            fields=[
                ('name', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=core.models.csrid, editable=False, max_length=11, primary_key=True, serialize=False, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csr_representatives', to='core.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('name', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=core.models.cvid, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20)),
                ('main_language', models.CharField(choices=[('en', 'English'), ('zh', 'Chinese'), ('ta', 'Tamil'), ('ms', 'Malay')], max_length=20)),
                ('second_language', models.CharField(blank=True, choices=[('en', 'English'), ('zh', 'Chinese'), ('ta', 'Tamil'), ('ms', 'Malay')], max_length=20)),
                ('service_category_preference', models.CharField(choices=[('Healthcare', 'Healthcare'), ('Therapy', 'Therapy'), ('Dialysis', 'Dialysis'), ('Vaccination / Check-up', 'Vaccination / Check-up'), ('Mobility Assistance', 'Mobility Assistance'), ('Community Event', 'Community Event')], max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='core.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClaimReport',
            fields=[
                ('id', models.CharField(default=core.models.claimid, editable=False, max_length=11, primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(choices=[('transport', 'Transportation'), ('food', 'Food'), ('meds', 'Medication'), ('appointment', 'Appointment'), ('other', 'Other')], max_length=20)),
                ('expense_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('paynow', 'Bank Paynow'), ('paylah', 'DBS PayLah')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=600)),
                ('receipt', models.FileField(upload_to='receipts/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('verified_by_pin', 'Verified by PIN'), ('disputed_by_pin', 'Disputed by PIN'), ('rejected_by_csr', 'Rejected by CSR'), ('reimbursed_by_csr', 'Reimbursed by CSR')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='core.cv')),
            ],
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('profile_update', 'Profile Update'), ('password_change', 'Password Change')], max_length=30)),
                ('expires_at', models.DateTimeField()),
                ('consumed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'purpose', 'expires_at', 'consumed'], name='core_emailo_email_7b988a_idx')],
            },
        ),
        migrations.CreateModel(
            name='PA',
            fields=[
                ('name', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=core.models.pa_id, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonInNeed',
            fields=[
                ('name', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=core.models.pinid, editable=False, max_length=11, primary_key=True, serialize=False, unique=True)),
                ('preferred_cv_language', models.CharField(choices=[('en', 'English'), ('zh', 'Chinese'), ('ta', 'Tamil'), ('ms', 'Malay')], max_length=20)),
                ('preferred_cv_gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClaimDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('incorrect_amount', 'Incorrect amount'), ('never_happened', 'Never happened'), ('incorrect_item', 'Incorrect item'), ('description_error', 'Description error')], max_length=50)),
                ('comment', models.CharField(blank=True, max_length=600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='core.claimreport')),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_disputes', to='core.personinneed')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.CharField(default=core.models.reqid, editable=False, max_length=11, primary_key=True, serialize=False, unique=True)),
                ('service_type', models.CharField(choices=[('Healthcare', 'Healthcare'), ('Therapy', 'Therapy'), ('Dialysis', 'Dialysis'), ('Vaccination / Check-up', 'Vaccination / Check-up'), ('Mobility Assistance', 'Mobility Assistance'), ('Community Event', 'Community Event')], help_text='Type of service requested.', max_length=50)),
                ('appointment_date', models.DateField(help_text='Date of appointment.')),
                ('appointment_time', models.TimeField(help_text='Time of appointment.')),
                ('pickup_location', models.CharField(max_length=255)),
                ('service_location', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=700)),
                ('status', models.CharField(choices=[('review', 'Review'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('active', 'Active'), ('complete', 'Complete')], default='review', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('committed_by_csr', models.ForeignKey(blank=True, help_text='CSR who committed this request for matching.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committed_requests', to='core.csrrep')),
                ('cv', models.ForeignKey(blank=True, help_text='Matched CV', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='core.cv')),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.personinneed')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('offer_sent', 'Offer sent to CV'), ('offer_declined', 'CV declined'), ('offer_expired', 'CV did not respond (expired)'), ('queue_advanced', 'Reassigned to next CV'), ('match_accepted', 'CV accepted — match created'), ('match_filled', 'Queue filled (request active)'), ('queue_started', 'Queue started')], max_length=32)),
                ('message', models.CharField(max_length=300)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('cv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cv')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.request')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_index', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('filled', 'Filled'), ('exhausted', 'Exhausted')], default='pending', max_length=12)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('cv1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.cv')),
                ('cv2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.cv')),
                ('cv3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.cv')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_queue', to='core.request')),
            ],
        ),
        migrations.CreateModel(
            name='FlaggedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('auto', 'Auto-Flagged'), ('manual', 'Manually Flagged by CSR')], max_length=10)),
                ('reasonbycsr', models.TextField(blank=True, help_text='Why this was flagged (auto reason or CSR comment).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolution_outcome', models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], help_text='Whether PA accepted or rejected this flag.', max_length=10, null=True)),
                ('csr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags_made', to='core.csrrep')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags_resolved', to='core.pa')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='core.request')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='claimreport',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='core.request'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='core.request'),
        ),
        migrations.CreateModel(
            name='ShortlistedRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('csr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlists', to='core.csrrep')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_by', to='core.request')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['status'], name='core_reques_status_27d5ad_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['appointment_date', 'appointment_time'], name='core_reques_appoint_fd800d_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['pin'], name='core_reques_pin_id_e15cb2_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['committed_by_csr', 'status'], name='core_reques_committ_49a33b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='core_notifi_recipie_aeffaf_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'created_at'], name='core_notifi_recipie_4a67cf_idx'),
        ),
        migrations.AddIndex(
            model_name='flaggedrequest',
            index=models.Index(fields=['flag_type'], name='core_flagge_flag_ty_db5505_idx'),
        ),
        migrations.AddIndex(
            model_name='flaggedrequest',
            index=models.Index(fields=['created_at'], name='core_flagge_created_3fc087_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['opens_at'], name='core_chatro_opens_a_d79198_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['expires_at'], name='core_chatro_expires_674e5d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['created_at'], name='core_chatro_created_412b6b_idx'),
        ),
        migrations.AddIndex(
            model_name='shortlistedrequest',
            index=models.Index(fields=['csr'], name='core_shortl_csr_id_1ead5e_idx'),
        ),
        migrations.AddIndex(
            model_name='shortlistedrequest',
            index=models.Index(fields=['request'], name='core_shortl_request_469981_idx'),
        ),
        migrations.AddIndex(
            model_name='shortlistedrequest',
            index=models.Index(fields=['-created_at'], name='core_shortl_created_427cf7_idx'),
        ),
        migrations.AddConstraint(
            model_name='shortlistedrequest',
            constraint=models.UniqueConstraint(fields=('csr', 'request'), name='uq_shortlist_csr_request'),
        ),
    ]
