# Generated by Django 5.2.7 on 2025-11-05 08:45

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=50, unique=True)),
                ('companyname', models.CharField(max_length=200)),
                ('JoinedDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CSRRep',
            fields=[
                ('name', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=core.models.csrid, editable=False, max_length=11, primary_key=True, serialize=False, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csr_representatives', to='core.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('name', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=core.models.cvid, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20)),
                ('main_language', models.CharField(choices=[('en', 'English'), ('zh', 'Chinese'), ('ta', 'Tamil'), ('ms', 'Malay')], max_length=20)),
                ('second_language', models.CharField(blank=True, choices=[('en', 'English'), ('zh', 'Chinese'), ('ta', 'Tamil'), ('ms', 'Malay')], max_length=20)),
                ('service_category_preference', models.CharField(choices=[('Healthcare', 'Healthcare'), ('Therapy', 'Therapy'), ('Dialysis', 'Dialysis'), ('Vaccination / Check-up', 'Vaccination / Check-up'), ('Mobility Assistance', 'Mobility Assistance'), ('Community Event', 'Community Event')], max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='core.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PA',
            fields=[
                ('name', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=core.models.pa_id, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonInNeed',
            fields=[
                ('name', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=core.models.pinid, editable=False, max_length=11, primary_key=True, serialize=False, unique=True)),
                ('preferred_cv_language', models.CharField(choices=[('en', 'English'), ('zh', 'Chinese'), ('ta', 'Tamil'), ('ms', 'Malay')], max_length=20)),
                ('preferred_cv_gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.CharField(default=core.models.reqid, editable=False, max_length=11, primary_key=True, serialize=False, unique=True)),
                ('service_type', models.CharField(choices=[('Healthcare', 'Healthcare'), ('Therapy', 'Therapy'), ('Dialysis', 'Dialysis'), ('Vaccination / Check-up', 'Vaccination / Check-up'), ('Mobility Assistance', 'Mobility Assistance'), ('Community Event', 'Community Event')], help_text='Type of service requested.', max_length=50)),
                ('appointment_date', models.DateField(help_text='Date of appointment.')),
                ('appointment_time', models.TimeField(help_text='Time of appointment.')),
                ('pickup_location', models.CharField(max_length=255)),
                ('service_location', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=700)),
                ('status', models.CharField(choices=[('review', 'Review'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('active', 'Active'), ('complete', 'Complete')], default='review', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cv', models.ForeignKey(blank=True, help_text='Matched CV', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='core.cv')),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.personinneed')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlaggedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('auto', 'Auto-Flagged'), ('manual', 'Manually Flagged by CSR')], max_length=10)),
                ('reason', models.TextField(blank=True, help_text='Why this was flagged (auto reason or CSR comment).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('csr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags_made', to='core.csrrep')),
                ('resolved_by', models.ForeignKey(blank=True, help_text='PA who resolved the flag.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags_resolved', to='core.pa')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='core.request')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['status'], name='core_reques_status_27d5ad_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['appointment_date', 'appointment_time'], name='core_reques_appoint_fd800d_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['pin'], name='core_reques_pin_id_e15cb2_idx'),
        ),
        migrations.AddIndex(
            model_name='flaggedrequest',
            index=models.Index(fields=['flag_type'], name='core_flagge_flag_ty_db5505_idx'),
        ),
        migrations.AddIndex(
            model_name='flaggedrequest',
            index=models.Index(fields=['created_at'], name='core_flagge_created_3fc087_idx'),
        ),
    ]
