# Generated by Django 5.2.8 on 2025-11-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='core_notifi_recipie_aeffaf_idx',
        ),
        migrations.RenameField(
            model_name='matchqueue',
            old_name='cv1',
            new_name='cv1queue',
        ),
        migrations.RenameField(
            model_name='matchqueue',
            old_name='cv2',
            new_name='cv2queue',
        ),
        migrations.RenameField(
            model_name='matchqueue',
            old_name='cv3',
            new_name='cv3queue',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('offer_sent', 'Offer sent to CV'), ('offer_declined', 'CV declined'), ('offer_expired', 'CV did not respond (expired)'), ('queue_advanced', 'Reassigned to next CV'), ('match_accepted', 'CV accepted — match created')], max_length=32),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('review', 'Review'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('committed', 'Committed'), ('active', 'Active'), ('complete', 'Complete')], default='review', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='request',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'committed'), _negated=True), models.Q(('committed_by_csr__isnull', False), ('committed_at__isnull', False)), _connector='OR'), name='req_committed_has_committer'),
        ),
        migrations.AddConstraint(
            model_name='request',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'pending'), _negated=True), models.Q(('committed_by_csr__isnull', True), ('committed_at__isnull', True)), _connector='OR'), name='req_pending_not_committed'),
        ),
    ]
