# Generated by Django 5.2.8 on 2025-11-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_request_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('offer_sent', 'Offer sent to CV'), ('offer_declined', 'CV declined'), ('offer_expired', 'CV did not respond (expired)'), ('queue_advanced', 'Reassigned to next CV'), ('match_accepted', 'CV accepted — match created'), ('no_match_found', 'No match found from queue')], max_length=32),
        ),
    ]
